### ISSUE TITLE
Make --destination-filepath optional for add dataset

### ISSUE THREAD

**Issue by coleslaw481** [fairscape/fairscape-cli#6]
For `fairscape-cli rocrate add dataset` command make the option `--destination-filepath` optional if the `--source-filepath` specified is already within the crate. 

This is needed to eliminate duplicate files for the use case where the data is already in a directory that is an `rocrate`

**Comment by mlev71** [comment]
- Issue is when there is stuff inside the crate already and doesn't need to be moved

Will move a command to annotate or some other verb, for stuff already inside the crate.

**Comment by mlev71** [comment]
With the command register, you can now add anotations to the ro-crate-metadata.json without copying the any files over.

E.G. 
```bash
fairscape-cli rocrate register dataset \
  --guid 'ark:59853/UVA/B2AI/rocrate_test/music_data' \
  --name 'AP-MS embeddings' \
  --description 'Example node2vec embeddings from APMS data' \
  --date-published '05-12-2023' \
  --author 'max levinson' \
  --version '1.0.0' \
  --data-format '.csv' \
  --filepath './tests/example_rocrate/APMS_embedding_MUSIC.csv' \
  './tests/example_rocrate'
```
