### ISSUE TITLE
fairscape rocrate register software still requires --file-path

### ISSUE THREAD

**Issue by coleslaw481** [fairscape/fairscape-cli#8]
Is it possible to make `--file-path` optional if `--url` is set for registering software?

I want to be able to run this:

```bash
fairscape-cli rocrate register software --name 'sometool' \
 --author 'bob smith' --version '0.1.0' --description 'some description' \
 --file-format '.py' --url 'https://github.com/ndexbio/ndex2-client' `pwd`
```

**Comment by mlev71** [comment]
Fixed in commit 72e6278595c20f801eb1b9f7c68b4f75be1c633c.
Leaving this open until built and tested.
