### ISSUE TITLE
Registration of dataset slow

### ISSUE THREAD

**Issue by coleslaw481** [fairscape/fairscape-cli#9]
I am noticing on my machine (version 0.1.5a1) that it takes about 0.2 seconds to register a single dataset that is already in a rocrate. Problem is I have 100,000 images to register and this on its own will take over 5 hours to do. Is there a way to speed this up?

**Comment by mlev71** [comment]
I will set up some benchmarks.
As for the cause I have my suspicions about opening and overwriting the ro-crate-metadata.json file.
Though I use a context manager for opening the file, reading it in and writing the file back.
It shouldn't be that slow to register a single object.

I can rewrite it so it only opens the file once in `mode='rw'` and then uses one file object.

Pydantic and the parsing is based in rust now, so I doubt that is it.
Click is similarly not a bottleneck, so I'm gonna focus on testing the ROCrate method registerObject

**Comment by mlev71** [comment]
I noticed I did some unwise things just to get stuff done quicker.

The new ROCrate class method registerObject now only opens the file once, and uses json.dump to write directly to the file.
